name: coverage
on:
  push:
    branches:
      - master
jobs:
  perl6:
    runs-on: ubuntu-latest
    container:
      image: fernandocorrea/red-tester-no-run
    steps:
      - uses: actions/checkout@v2
      - name: Run test coverage
        run: |
          racoco --fail-level=$(cat .coverage) --exec='zef test -v .' --html | raku -ne 'say $<num>.floor if /^ "Coverage:" <.ws> $<num>=[\d+\.\d+] "%" $/' > .coverage
          rm -rf docs/coverage
          mkdir -p docs/coverage/
          mv .racoco/* docs/coverage/
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Coverage" -a || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
