name: test
on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:
jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        raku-version:
          - "2022.07"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - run: raku -V
      - name: Cache zef dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.raku
            ~/.zef
          key: ${{ runner.os }}-zef-${{ hashFiles('META6.json') }}
          restore-keys: |
            ${{ runner.os }}-zef-
      - name: Pre-install core dependencies
        run: |
          # Install dependencies that are commonly needed and cache them
          zef install --/test Config Config::Parser::json App::Prove6 || true
      - name: Install dependencies
        run: |
          zef install --/test --test-depends --deps-only .
          zef install --/test App::Prove6
      - name: Run tests
        run: prove6 -lj8 t

  pg:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: red_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v3
      - uses: Raku/setup-raku@v1
        with:
          raku-version: "2022.07"
      - name: Cache zef dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.raku
            ~/.zef
          key: ${{ runner.os }}-zef-pg-${{ hashFiles('META6.json') }}
          restore-keys: |
            ${{ runner.os }}-zef-pg-
            ${{ runner.os }}-zef-
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev postgresql-client
      - name: Pre-install core dependencies
        run: |
          # Install dependencies that are commonly needed and cache them
          zef install --/test Config Config::Parser::json App::Prove6 DB::Pg || true
      - name: Install Raku deps
        run: |
          zef install --/test --test-depends --deps-only .
          zef install --/test App::Prove6 DB::Pg
      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h 127.0.0.1 -p 5432 -U postgres && break
            sleep 1
          done
      - name: Show psql version
        run: psql --version
      - name: Run tests (Pg)
        env:
          RED_DATABASE: "Pg host=127.0.0.1 port=5432 dbname=red_test user=postgres password=postgres"
        run: prove6 -lj2 t